// Python `stick` module — narrow binding surface exposed to .stickapp code.
//
// This file is compiled twice:
//   1. During the MicroPython embed build (regenerated by build_mpy_vm.sh)
//      purely so its QSTR references land in the generated qstr table.
//   2. As part of the Arduino library build, which is where it actually
//      executes. The implementations of stick_bind_* live in
//      stick_bindings.cpp alongside the library.
//
// Only add symbols that map to a concrete binding function — every name
// here is a forward-compatibility promise.

#include "py/obj.h"
#include "py/runtime.h"

#include "stick_bindings.h"

// ---- Timing ----

static mp_obj_t stick_millis(void) {
    return mp_obj_new_int_from_uint(stick_bind_millis());
}
static MP_DEFINE_CONST_FUN_OBJ_0(stick_millis_obj, stick_millis);

static mp_obj_t stick_delay(mp_obj_t ms_in) {
    stick_bind_delay((uint32_t)mp_obj_get_int(ms_in));
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(stick_delay_obj, stick_delay);

static mp_obj_t stick_exit(void) {
    return mp_obj_new_bool(stick_bind_should_exit());
}
static MP_DEFINE_CONST_FUN_OBJ_0(stick_exit_obj, stick_exit);

// ---- Module table ----

static const mp_rom_map_elem_t stick_module_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_stick) },
    { MP_ROM_QSTR(MP_QSTR_millis),   MP_ROM_PTR(&stick_millis_obj) },
    { MP_ROM_QSTR(MP_QSTR_delay),    MP_ROM_PTR(&stick_delay_obj) },
    { MP_ROM_QSTR(MP_QSTR_exit),     MP_ROM_PTR(&stick_exit_obj) },
};
static MP_DEFINE_CONST_DICT(stick_module_globals, stick_module_globals_table);

const mp_obj_module_t stick_user_cmodule = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t *)&stick_module_globals,
};

MP_REGISTER_MODULE(MP_QSTR_stick, stick_user_cmodule);
