#!/usr/bin/env bash
# Regenerate .clangd at repo root so clangd knows Arduino's include paths.
#
# We can't commit a single .clangd that works for every developer —
# arduino-cli resolves absolute paths into the local Arduino15 install
# (and every machine puts it somewhere slightly different). This script
# dumps the exact -I and -D flags that arduino-cli uses to compile the
# sketch, filters out xtensa-specific codegen flags that a host clangd
# shouldn't see, and writes a .clangd YAML.
#
# Run after:
#   - installing a new library
#   - updating the M5Stack / ESP32 core
#   - moving ~/Documents/Arduino or ~/Library/Arduino15
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

FQBN="m5stack:esp32:m5stack_stickc_plus2"
SKETCH="os"
OUT="$REPO_ROOT/.clangd"

VERBOSE_LOG="$(mktemp)"
trap 'rm -f "$VERBOSE_LOG"' EXIT

echo "running arduino-cli compile --verbose (this takes ~1 minute)..."
arduino-cli compile --fqbn "$FQBN" \
  --libraries "$REPO_ROOT/libraries" \
  --verbose "$SKETCH" > "$VERBOSE_LOG" 2>&1

{
  echo "# clangd project config — generated by tools/gen_clangd.sh"
  echo "# Gitignored; paths are user-specific."
  echo "CompileFlags:"
  echo "  Add:"
  # Single-quoted YAML so embedded " in defines (e.g. -DX="value") doesn't
  # break parsing. Any literal ' inside flags is escaped by doubling.
  grep -oE '\-I[^ ]+' "$VERBOSE_LOG" | sort -u \
    | awk "{gsub(/'/, \"''\"); print \"    - '\" \$0 \"'\"}"
  echo "  # Preprocessor defines"
  # arduino-cli logs every compile command twice — once with raw quotes
  # and once shell-escaped for display. Drop the shell-escaped version
  # (it contains \").
  grep -oE '\-D[A-Z_][A-Za-z0-9_]*(=(\"[^\"]*\"|[^ ]*))?' "$VERBOSE_LOG" \
    | grep -v '\\"' | sort -u \
    | awk "{gsub(/'/, \"''\"); print \"    - '\" \$0 \"'\"}"
  cat <<'EOF'
  # xtensa-only codegen flags — clangd is analysing on the host.
  Remove:
    - "-mlongcalls"
    - "-mtext-section-literals"
    - "-fno-tree-switch-conversion"
    - "-fstrict-volatile-bitfields"
    - "-free"
    - "-ffreestanding"

Diagnostics:
  Suppress:
    # Cross-compile header-not-found noise. Real #include errors from
    # our own code still surface as semantic diagnostics (undeclared
    # identifier etc.).
    - "pp_file_not_found"
EOF
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
